extern Vtx gGiDarkRelicDL_gGiDarkRelicDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gGiDarkRelicDL_gGiDarkRelicDL_mesh_layer_Opaque_vtx_0[130];
extern Gfx gGiDarkRelicDL_gGiDarkRelicDL_mesh_layer_Opaque_tri_0[];
extern Vtx gGiDarkRelicDL_gGiDarkRelicDL_mesh_layer_Opaque_vtx_1[105];
extern Gfx gGiDarkRelicDL_gGiDarkRelicDL_mesh_layer_Opaque_tri_1[];
extern Gfx mat_gGiDarkRelicDL_f3dlite_material_001_layerOpaque[];
extern Gfx mat_gGiDarkRelicDL_f3dlite_material_004_layerOpaque[];
extern Gfx gGiDarkRelicDL[];
